
[general]
import = ["~/.config/alacritty/fonts.toml"]
live_config_reload = true

[window]
opacity=0.5

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window.padding]
x = 15
y = 10

[scrolling]
history = 10000
multiplier = 3


