[window]
opacity = 0.7
blur = true

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Agave Nerd Font"
bold.family = "Agave Nerd Font"
italic.family = "Agave Nerd Font"
bold_italic.family = "Agave Nerd Font"

size = 18.0
